-- MySQL Script generated by MySQL Workbench
-- Fri Oct 22 11:37:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbcelulares
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbcelulares` ;

-- -----------------------------------------------------
-- Schema dbcelulares
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcelulares` DEFAULT CHARACTER SET utf8 ;
USE `dbcelulares` ;

-- -----------------------------------------------------
-- Table `dbcelulares`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcelulares`.`EMPLEADO` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `ci` VARCHAR(10) NOT NULL,
  `cargo` VARCHAR(20) NOT NULL,
  `num_celular` INT NOT NULL,
  `fecha_inicio_contrato` DATE NOT NULL,
  `fecha_finalizacion_contrato` DATE NOT NULL,
  `correo` VARCHAR(40) NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `genero` VARCHAR(15) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcelulares`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcelulares`.`CLIENTE` (
  `ci` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `celular` INT NOT NULL,
  `direccion` VARCHAR(50) NULL,
  `correo` VARCHAR(40) NULL,
  `nit` INT NULL,
  PRIMARY KEY (`ci`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcelulares`.`PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcelulares`.`PROVEEDOR` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `celular` INT NOT NULL,
  `direccion` VARCHAR(50) NULL,
  `correo` VARCHAR(40) NULL,
  `ci` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcelulares`.`ACCESORIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcelulares`.`ACCESORIO` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcelulares`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcelulares`.`PRODUCTO` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `modelo` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(80) NOT NULL,
  `precio` DECIMAL(2,2) NOT NULL,
  `garantia` VARCHAR(10) NOT NULL,
  `gama` VARCHAR(12) NOT NULL,
  `PROVEEDOR_codigo` INT NOT NULL,
  `ACCESORIO_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_PRODUCTO_PROVEEDOR1`
    FOREIGN KEY (`PROVEEDOR_codigo`)
    REFERENCES `dbcelulares`.`PROVEEDOR` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_ACCESORIO1`
    FOREIGN KEY (`ACCESORIO_codigo`)
    REFERENCES `dbcelulares`.`ACCESORIO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PRODUCTO_PROVEEDOR1_idx` ON `dbcelulares`.`PRODUCTO` (`PROVEEDOR_codigo` ASC) VISIBLE;

CREATE INDEX `fk_PRODUCTO_ACCESORIO1_idx` ON `dbcelulares`.`PRODUCTO` (`ACCESORIO_codigo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcelulares`.`VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcelulares`.`VENTA` (
  `codigo` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `monto_cobrado` DECIMAL(3,2) NOT NULL,
  `cantidad_producto` INT NOT NULL,
  `EMPLEADO_codigo` INT NOT NULL,
  `CLIENTE_ci` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_VENTA_EMPLEADO`
    FOREIGN KEY (`EMPLEADO_codigo`)
    REFERENCES `dbcelulares`.`EMPLEADO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTA_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ci`)
    REFERENCES `dbcelulares`.`CLIENTE` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_VENTA_EMPLEADO_idx` ON `dbcelulares`.`VENTA` (`EMPLEADO_codigo` ASC) VISIBLE;

CREATE INDEX `fk_VENTA_CLIENTE1_idx` ON `dbcelulares`.`VENTA` (`CLIENTE_ci` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbcelulares`.`DETALLE_VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcelulares`.`DETALLE_VENTA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PRODUCTO_codigo` INT NOT NULL,
  `VENTA_codigo` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_VENTA_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_codigo`)
    REFERENCES `dbcelulares`.`PRODUCTO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTA_has_PRODUCTO_VENTA1`
    FOREIGN KEY (`VENTA_codigo`)
    REFERENCES `dbcelulares`.`VENTA` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_VENTA_has_PRODUCTO_PRODUCTO1_idx` ON `dbcelulares`.`DETALLE_VENTA` (`PRODUCTO_codigo` ASC) VISIBLE;

CREATE INDEX `fk_VENTA_has_PRODUCTO_VENTA1_idx` ON `dbcelulares`.`DETALLE_VENTA` (`VENTA_codigo` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
